Repository openshift/kubernetes-drain, pull requests merged in 2019-07, with the labels that each got.

#1 Fix getPodFn namespace issue
  drain.go
Labels: size/XS

#2 Update daemonsets to apps/v1 from extensions
  drain.go
  drain_test.go
Labels: size/S

#3 Bug 1732929: Fix eviction failure scenario
  drain.go
Labels: bugzilla/valid-bug, lgtm, size/M
